'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "날씨앱",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // 리액트에서 상태관리와 캐싱을 도와주는 라이브러리
  const queryClient = new QueryClient();

  return (
    <html lang="ko">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
